spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/springboot-sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 6379

order:
  name: this project is about user. it's task is save and get user.

